import { describe, expect, it } from "vitest";
import { recordDecision, type DecisionAuditRecord } from "../record.js";
import { replay } from "../replay.js";
import { parseAuditRecord } from "../validation.js";
import type { SignalSnapshot } from "../snapshot.js";
import { fixtureInput, fixtureRequirement, fixtureSignal, NOW } from "./fixtures.js";

/**
 * Audit-layer coverage for value constraints
 * (`.genesis/decisions/0004-value-constraints.md`): the record names the
 * constraint and its failure but never the raw value (M5's own
 * value-hiding guarantee, re-proven here for the new gap reason), and a
 * value-rejection decision replays exactly, the same as every other
 * outcome.
 */

const ID = "audit-value-constraint";
const RECORDED_AT = NOW;
const SECRET_VALUE = "fraudulent — card ending 4111, do not disclose this string";

function fraudInputRejecting() {
  return fixtureInput({
    requirements: [
      fixtureRequirement({
        signalKind: "fraud.assessment",
        description: "the fraud assessment for this transfer",
        valueConstraint: { op: "equals", value: "clear" },
        supplier: { kind: "human", reason: "should never be reached — value-rejected pre-empts supplier dispatch" },
      }),
    ],
    signals: [
      fixtureSignal({
        id: "fraud-sig-1",
        kind: "fraud.assessment",
        value: SECRET_VALUE,
        confidence: 0.95,
        capturedAtIso: "2026-09-19T11:00:00Z",
      }),
    ],
  });
}

/** Same mutation-proof structural shape check record.test.ts uses (not reproduced by import — that helper is local, not exported; reproducing it keeps this file self-contained, matching this project's own established convention of small, per-file boundary helpers over sharing test internals). */
function assertPlainSignalSnapshot(entry: SignalSnapshot): void {
  expect(Object.keys(entry).sort()).toEqual(["capturedAt", "confidence", "id", "kind", "source"]);
  expect("value" in entry).toBe(false);
  for (const key of Object.keys(entry)) {
    expect(typeof (entry as unknown as Record<string, unknown>)[key]).not.toBe("function");
  }
}

function asDecisionRecord(input: ReturnType<typeof fixtureInput>): DecisionAuditRecord {
  const record = recordDecision(input, ID, RECORDED_AT);
  if (record.kind !== "decision") throw new Error("expected a DecisionAuditRecord in this test");
  return record;
}

describe("recordDecision — a value-rejection decision is recorded with its rule, never its value", () => {
  it("rule.kind is 'value-rejected', naming the constraint and the signal that failed it", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    expect(record.decision.outcome).toBe("escalate");
    expect(record.rule).toEqual({
      kind: "value-rejected",
      requirementSignalKind: "fraud.assessment",
      signalId: "fraud-sig-1",
      constraint: { op: "equals", value: "clear" },
    });
  });

  it("the record's evidence is plain SignalSnapshot metadata only — structurally, not by string search", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    expect(record.decision.evidence).toHaveLength(1);
    for (const entry of record.decision.evidence) {
      assertPlainSignalSnapshot(entry);
    }
  });

  it("neither the record nor its rule contains the raw signal value anywhere, even as a substring", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    const serialized = JSON.stringify(record);
    expect(serialized).not.toContain(SECRET_VALUE);
    expect(serialized).not.toContain("4111");
    // The escalate reason text is prose, generated by reasons.ts — it
    // must not have smuggled the value in either.
    if (record.decision.outcome === "escalate") {
      expect(record.decision.missing.reason).not.toContain(SECRET_VALUE);
      expect(record.decision.missing.reason).not.toContain("4111");
    }
  });

  it("the value stays reachable ONLY through discloseSignalValue against the original signal — never through the record", async () => {
    const { discloseSignalValue } = await import("../disclose.js");
    const input = fraudInputRejecting();
    const originalSignal = input.signals[0];
    if (originalSignal === undefined) throw new Error("fixture should have exactly one signal");

    const disclosure = discloseSignalValue(originalSignal, input.requirements[0]!.maxAge, input.now);
    expect(disclosure.reading).toEqual({
      status: "fresh",
      value: SECRET_VALUE,
      age: expect.any(Number),
      confidence: expect.any(Number),
    });
  });
});

describe("replay — a value-rejection decision replays exactly, like every other outcome", () => {
  it("replaying with the same (empty) prohibition set reproduces the recorded escalate decision", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    const result = replay(record, []);

    expect(result.ruleSetMatches).toBe(true);
    expect(result.matches).toBe(true);
    expect(result.replayed).toEqual(record.decision);
  });

  it("the replayed decision's evidence is still metadata-only (reconstructed via fromSignalSnapshot, UNDISCLOSED_VALUE never leaks)", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    const result = replay(record, []);

    if ("evidence" in result.replayed) {
      for (const entry of result.replayed.evidence) {
        assertPlainSignalSnapshot(entry);
      }
    }
  });

  it("STATED LIMITATION, proven rather than assumed: metadata-only replay of an EXECUTE decision that depended on a constraint being CLEARED does not reproduce it — the value that made it agree is never recorded, by design", () => {
    const requirement = fixtureRequirement({
      signalKind: "fraud.assessment",
      valueConstraint: { op: "equals", value: "clear" },
    });
    const cleanSignal = fixtureSignal({
      id: "fraud-clean-1",
      kind: "fraud.assessment",
      value: "clear",
      confidence: 0.95,
      capturedAtIso: "2026-09-19T11:00:00Z",
    });
    const record = asDecisionRecord(fixtureInput({ requirements: [requirement], signals: [cleanSignal] }));
    expect(record.decision.outcome).toBe("execute");

    // No `knownSignals` supplied — replay can only reconstruct metadata,
    // so it cannot re-verify the constraint was cleared. This is an
    // HONEST, DETECTABLE divergence (ruleSetMatches still true; matches
    // false) — never a silent false match, and never a crash.
    const result = replay(record, []);
    expect(result.ruleSetMatches).toBe(true);
    expect(result.matches).toBe(false);
  });

  it("supplying the REAL signal via replay's optional third parameter (knownSignals) restores full fidelity — the same precedent ADR 0003 already set for Prohibitions, applied to values", () => {
    const requirement = fixtureRequirement({
      signalKind: "fraud.assessment",
      valueConstraint: { op: "equals", value: "clear" },
    });
    const cleanSignal = fixtureSignal({
      id: "fraud-clean-2",
      kind: "fraud.assessment",
      value: "clear",
      confidence: 0.95,
      capturedAtIso: "2026-09-19T11:00:00Z",
    });
    const record = asDecisionRecord(fixtureInput({ requirements: [requirement], signals: [cleanSignal] }));
    expect(record.decision.outcome).toBe("execute");

    const result = replay(record, [], [cleanSignal]);
    expect(result.ruleSetMatches).toBe(true);
    expect(result.matches).toBe(true);
    expect(result.replayed).toEqual(record.decision);
  });

  it("a knownSignal whose id matches but whose OWN metadata does not is rejected, not silently substituted", () => {
    const requirement = fixtureRequirement({
      signalKind: "fraud.assessment",
      valueConstraint: { op: "equals", value: "clear" },
    });
    const cleanSignal = fixtureSignal({
      id: "fraud-clean-3",
      kind: "fraud.assessment",
      value: "clear",
      confidence: 0.95,
      capturedAtIso: "2026-09-19T11:00:00Z",
    });
    const record = asDecisionRecord(fixtureInput({ requirements: [requirement], signals: [cleanSignal] }));

    // Same id, but a different confidence — not honestly "the same
    // evidence, now disclosed".
    const impostor = fixtureSignal({
      id: "fraud-clean-3",
      kind: "fraud.assessment",
      value: "clear",
      confidence: 0.5,
      capturedAtIso: "2026-09-19T11:00:00Z",
    });

    const result = replay(record, [], [impostor]);
    // Falls back to metadata-only reconstruction, so it inherits the
    // same honest limitation as the no-knownSignals case above, rather
    // than trusting the impostor's confidence.
    expect(result.matches).toBe(false);
  });

  it("a value-rejection (constraint NOT cleared) replays exactly even WITHOUT knownSignals — the wording collapse (reasons.ts) makes metadata alone sufficient for a rejection", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    const result = replay(record, []); // deliberately no knownSignals
    expect(result.matches).toBe(true);
  });
});

describe("parseAuditRecord — a value-rejection record round-trips through JSON", () => {
  it("a decision record whose requirement declares a valueConstraint, and whose rule is value-rejected, survives JSON.stringify/JSON.parse", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    const raw = JSON.parse(JSON.stringify(record));
    const parsed = parseAuditRecord(raw, NOW);
    expect(parsed.ok).toBe(true);
    if (parsed.ok) {
      expect(parsed.value).toEqual(record);
    }
  });

  it("a Requirement with NO valueConstraint still round-trips (the field is genuinely optional, never defaulted to a bogus value)", () => {
    const record = asDecisionRecord(
      fixtureInput({ requirements: [fixtureRequirement({ minConfidence: 0.1 })], signals: [fixtureSignal({ confidence: 0.95 })] }),
    );
    const raw = JSON.parse(JSON.stringify(record));
    const parsed = parseAuditRecord(raw, NOW);
    expect(parsed.ok).toBe(true);
    if (parsed.ok && parsed.value.kind === "decision") {
      expect(parsed.value.requirements[0]).not.toHaveProperty("valueConstraint");
    }
  });

  it("a malformed valueConstraint on a requirement fails closed to a typed parse error, never throws", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    const raw = JSON.parse(JSON.stringify(record));
    raw.requirements[0].valueConstraint = { op: "not-a-real-op" };

    let result: ReturnType<typeof parseAuditRecord> | undefined;
    expect(() => {
      result = parseAuditRecord(raw, NOW);
    }).not.toThrow();
    expect(result!.ok).toBe(false);
  });

  it("a malformed 'value-rejected' rule falls back to internal-error rather than throwing or fabricating a constraint", () => {
    const record = asDecisionRecord(fraudInputRejecting());
    const raw = JSON.parse(JSON.stringify(record));
    raw.rule = { kind: "value-rejected", requirementSignalKind: "fraud.assessment" }; // missing signalId/constraint

    const result = parseAuditRecord(raw, NOW);
    expect(result.ok).toBe(true);
    if (result.ok && result.value.kind === "decision") {
      expect(result.value.rule).toEqual({ kind: "internal-error" });
    }
  });
});
